spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver # DB connection ??
  jpa:
    hibernate:
      ddl-auto: create # ???? table ??
    properties:
      hibernate:
        show_sql: true # sysout ?
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug # log?
    org.hibernate.type: trace # ????? ??? ???

